[[drone]]
id = 11
connected_node_ids = [12, 11]
pdr = 0.00

[[drone]]
id = 12
connected_node_ids = [11, 13]
pdr = 0.00

[[drone]]
id = 13
connected_node_ids = [12, 11, 14]
pdr = 0.00

[[drone]]
id = 14
connected_node_ids = [13]
pdr = 0.00

[[client]]
id = 4
connected_drone_ids = [13, 12]

[[client]]
id = 5
connected_drone_ids = [14]

[[server]]
id = 6
connected_drone_ids = [12, 11]