[[client]]
id = 11
connected_drone_ids = [21, 22]

[[drone]]
id = 21
connected_node_ids = [11, 31]
pdr = 0.00

[[drone]]
id = 22
connected_node_ids = [11, 31]
pdr = 0.00

[[drone]]
id = 31
connected_node_ids = [21, 22, 41]
pdr = 0.00

[[server]]
id = 41
connected_drone_ids = [31]