[[client]]
id = 11
connected_drone_ids = [21, 22]

[[client]]
id = 12
connected_drone_ids = [32, 33]

[[drone]]
id = 21
connected_node_ids = [11, 31, 42]
pdr = 0.00

[[drone]]
id = 22
connected_node_ids = [11, 31, 33]
pdr = 0.00

[[drone]]
id = 31
connected_node_ids = [21, 22, 32, 41, 42]
pdr = 0.00

[[drone]]
id = 32
connected_node_ids = [12, 31, 42]
pdr = 0.00

[[drone]]
id = 33
connected_node_ids = [12, 22, 41]
pdr = 0.00

[[server]]
id = 41
connected_drone_ids = [31, 33]

[[server]]
id = 42
connected_drone_ids = [21, 32]